resources:
- name: bit-bucket
  type: git
  source:
    branch: master
    uri: git@bitbucket.org:sonicdrivein/infra.git
    private_key: ((git_private_key))
- name: monthly
  type: time
  source: 
    interval: 720h
jobs:
- name: aws-checker
  plan:
  - get: bit-bucket
  - get: monthly
    trigger: true  
  - task: check_expiry_date
    file: bit-bucket/pcf_automation/aws-checker/aws-task.yml
    params:
      AWS_ACCESS_KEY_ID: ((access-key-id))
      AWS_SECRET_ACCESS_KEY: ((secret-access-key))
      Envi: ((envi))
      Username: ((Username-conf))
      Password: ((Password-conf))
      id: ((page-id-conf))
      url: ((url-conf))
      key: ((key-conf))
